# TODO
apiVersion: v1
kind: Namespace
metadata:
  name: bfall-me
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pangolin-gateway-controller
  namespace: bfall-me
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pangolin-gateway-controller
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses/status"]
    verbs: ["patch", "update"]

  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways/status"]
    verbs: ["patch", "update"]

  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes/status"]
    verbs: ["patch", "update"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
    resourceNames: ["pangolin-gateway-controller"]

  - apiGroups: ["bfall.me"]
    resources: ["pangolinconfigs"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pangolin-gateway-controller
subjects:
  - kind: ServiceAccount
    name: pangolin-gateway-controller
    namespace: bfall-me
roleRef:
  kind: ClusterRole
  name: pangolin-gateway-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pangolinconfigs.bfall.me
spec:
  group: bfall.me
  names:
    categories: []
    kind: PangolinConfig
    plural: pangolinconfigs
    shortNames: []
    singular: pangolinconfig
  scope: Cluster
  versions:
    - additionalPrinterColumns: []
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Configuration for the Pangolin gateway controller
          properties:
            spec:
              properties:
                api:
                  type: string
                apiKeyRef:
                  properties:
                    key:
                      type: string
                    name:
                      type: string
                    namespace:
                      nullable: true
                      type: string
                  required:
                    - key
                    - name
                  type: object
              required:
                - api
                - apiKeyRef
              type: object
          required:
            - spec
          title: PangolinConfig
          type: object
      served: true
      storage: true
      subresources: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pangolin-gateway-controller
  namespace: bfall-me
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pangolin-gateway-controller
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pangolin-gateway-controller
    spec:
      serviceAccountName: pangolin-gateway-controller
      containers:
        - name: pangolin-gateway-controller
          image: ghcr.io/weshnaw/bfall-kube-controller/pangolin-gateway-controller:master
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
