[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
derive_more.workspace = true
serde.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
metrics.workspace = true
kube.workspace = true
kube-leader-election.workspace = true
uuid.workspace = true

[features]
default = ["controller"]
controller = []
